services:
    backend:
        container_name: trackmix-backend
        build: ./backend
        env_file:
            - path: .env
              required: true
        volumes:
            - ./audio/:/audio
        depends_on:
            - database
        restart: unless-stopped

    frontend:
        container_name: trackmix-frontend-builder
        build: ./frontend
        profiles:
            - building
        env_file:
            - path: .env
              required: true
        volumes:
            # - ./frontend:/app
            - ./frontend/build:/app/build
        restart: "no"

    caddy:
        container_name: trackmix-caddy
        build: ./caddy
        env_file:
            - path: .env
              required: true
        ports:
            - 80:80
            - 443:3443
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./audio/:/audio
            - ./frontend/build:/static
        depends_on:
            - backend
            # - frontend
        restart: unless-stopped

    database:
        container_name: trackmix-database
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./database:/data/db
        env_file:
            - path: .env
              required: true
volumes:
    caddy_data:
        external: true
    caddy_config:
